require:
  - rubocop-rails
  - rubocop-erb
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - test/dummy/db/schema.rb

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 10
  Exclude:
    - "test/dummy/db/migrate/*.rb"
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - "config/environments/*.rb"
    - "test/**/*_test.rb"
    - "*.gemspec"
    - "config/routes.rb"
    - "Gemfile"

Metrics/ModuleLength:
  Exclude:
    - "**/concerns/**/*.rb"

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"

Rails/LexicallyScopedActionFilter:
  Exclude:
    - "**/concerns/**/*.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "test/**/*.rb"

Performance/MethodObjectAsBlock:
  Enabled: false

Style/NumberedParametersLimit:
  Max: 3
